/**
 * Script 模块 DTOs
 * 所有类型从 @pixaura/shared-types 导入，避免重复定义
 */

export {
  // 常量
  ScriptStatus,
  AITaskType,
  AITaskStatus,
  AssetType,
  AssetStatus,
  ParagraphType,
  CharacterImportance,
  ScriptSource,
  // Schema 子类型
  SceneSettingSchema,
  ImportedAssetSchema,
  CreationPlanSchema,
  CharacterRefSchema,
  SceneRefSchema,
  PropRefSchema,
  ScriptContentSchema,
  ImportInfoSchema,
  AssetSummarySchema,
  ScriptMetadataSchema,
  UpdateScriptDescriptionSchema,
  RegenerateScriptSchema,
  // Request DTO Schemas
  AIGenerateScriptSchema,
  ImportScriptSchema,
  ParseScriptSchema,
  CreateScriptSchema,
  UpdateScriptSchema,
  QueryScriptsSchema,
  ConfirmScriptSchema,
  AIContinueSchema,
  AIRewriteSchema,
  AIExpandSchema,
  AICondenseSchema,
  ImportAssetFromProjectSchema,
  QueryImportableAssetsSchema,
  // DTO Types
  // 注意：ScriptStatus, AITaskType 等常量已作为值导出，这里不再重复导出类型
  type SceneSetting,
  type ImportedAsset,
  type CreationPlan,
  type CharacterRef,
  type SceneRef,
  type PropRef,
  type ScriptContent,
  type ImportInfo,
  type AssetSummary,
  type ScriptMetadata,
  type AIGenerateScriptDto,
  type ImportScriptDto,
  type ParseScriptDto,
  type CreateScriptDto,
  type UpdateScriptDto,
  type QueryScriptsDto,
  type ConfirmScriptDto,
  type AIContinueDto,
  type AIRewriteDto,
  type AIExpandDto,
  type AICondenseDto,
  type ImportAssetFromProjectDto,
  type QueryImportableAssetsDto,
  // 剧本编辑页面重构新增类型
  type StepState,
  type GenerationState,
  type AssetImage,
  type CharacterRefWithImages,
  type SceneRefWithImages,
  type PropRefWithImages,
  type Dialogue,
  type StoryboardRef,
  type SoundEffect,
  type GetScriptEditDetailResponse,
  type UpdateScriptDescriptionDto,
  type UpdateScriptDescriptionResponse,
  type RegenerateScriptDto,
  type RegenerateScriptResponse,
  type GetTaskStatusResponse,
  type CancelTaskResponse,
  // 剧本模型配置类型
  type ScriptModelConfigItem,
  type GetScriptModelConfigsResponse,
  UpdateScriptModelConfigsSchema,
  type UpdateScriptModelConfigsDto,
  type UpdateScriptModelConfigsResponse,
  // Response DTOs
  type ScriptListItemDto,
  type ScriptDetailDto,
  type AITaskDto,
  type AIGenerateProgressDto,
  type ImportableAssetDto,
  type ImportAssetResultDto,
  type ScriptConfirmPreviewDto,
  // State
  type ScriptState,
} from "@pixaura/shared-types";
